In [35]:
import numpy as np
z = np.random.randint(0, 10, size = 4)

In [36]:
z.shape

(4,)

In [39]:
z

array([3, 9, 8, 0])

In [46]:
a = np.outer(z, z)

In [47]:
a

array([[ 9, 27, 24,  0],
       [27, 81, 72,  0],
       [24, 72, 64,  0],
       [ 0,  0,  0,  0]])

In [42]:
a.shape

(4, 4)

In [43]:
a = np.matmul(z, z.T)

In [51]:
z = np.random.randint(0, 10, size = (4, 4))

In [58]:
z

array([[5, 6, 0, 4],
       [4, 6, 7, 6],
       [6, 0, 6, 0],
       [9, 3, 9, 0]])

In [60]:
z[1, :]

array([4, 6, 7, 6])

In [55]:
np.sum(z, axis = 1)

array([15, 23, 12, 21])

In [27]:
a.shape

(3, 3)

In [18]:
np.diag(z)

array([0.79064658, 0.85127701])

In [69]:
b = np.arange(3)

In [70]:
a = np.random.randint(0, 10, size = (3, 4))

In [71]:
a

array([[2, 1, 2, 8],
       [7, 1, 6, 1],
       [6, 3, 2, 3]])

In [72]:
b

array([0, 1, 2])

In [75]:
b[:, np.newaxis]

array([[0],
       [1],
       [2]])

In [74]:
a - b[:, np.newaxis]

array([[2, 1, 2, 8],
       [6, 0, 5, 0],
       [4, 1, 0, 1]])