In [1]:
import numpy as np

In [7]:
X = np.random.randint(0, 5, size = (3, 2, 4, 4))

In [8]:
X

array([[[[2, 4, 2, 3],
         [3, 3, 1, 0],
         [2, 2, 2, 4],
         [1, 4, 4, 0]],

        [[1, 0, 0, 1],
         [3, 4, 2, 2],
         [2, 4, 4, 3],
         [0, 2, 1, 2]]],


       [[[0, 1, 0, 1],
         [1, 0, 4, 3],
         [2, 0, 4, 3],
         [0, 0, 2, 2]],

        [[2, 0, 2, 1],
         [2, 3, 1, 4],
         [4, 0, 4, 2],
         [2, 1, 2, 2]]],


       [[[1, 2, 3, 2],
         [2, 0, 2, 4],
         [4, 3, 4, 1],
         [1, 3, 3, 3]],

        [[1, 1, 4, 0],
         [4, 2, 3, 2],
         [1, 4, 2, 2],
         [0, 0, 2, 2]]]])

In [10]:
Xuv = X[:, 1, 0:2, 0:2]

In [12]:
Xuv

array([[[1, 0],
        [3, 4]],

       [[2, 0],
        [2, 3]],

       [[1, 1],
        [4, 2]]])

In [67]:
Xuv.shape

(3, 2, 2)

In [57]:
Xuvr = np.reshape(Xuv, (3, -1))

In [63]:
Xuvr

array([[1, 0, 3, 4],
       [2, 0, 2, 3],
       [1, 1, 4, 2]])

In [75]:
a012 = np.array(range(Xuv.shape[0]))

In [64]:
am = Xuvr.argmax(axis = 1)

In [65]:
am

array([3, 3, 2])

In [76]:
Xuvr[a012, am]

array([4, 3, 4])

In [68]:
ui = np.unravel_index(am, Xuv[0].shape)

In [69]:
ui

(array([1, 1, 1]), array([1, 1, 0]))

In [77]:
Xuv[a012, ui[0], ui[1]]

array([4, 3, 4])

In [74]:
X[a012, 1, ui[0], ui[1]]

array([4, 3, 4])